Repository GenomicMedLab/software-templates, pull requests merged in 2024-02, with the labels that each got.

#2 cicd: ignore assert check in tests
  python/{{cookiecutter.project_slug}}/pyproject.toml
Labels: priority:high

#7 docs(python): add more autodoc things and some URL fixes
  python/hooks/post_gen_project.py
  python/{{cookiecutter.project_slug}}/.readthedocs.yaml
  python/{{cookiecutter.project_slug}}/README.md
  python/{{cookiecutter.project_slug}}/docs/source/_templates/module_summary.rst
  python/{{cookiecutter.project_slug}}/docs/source/conf.py
  python/{{cookiecutter.project_slug}}/docs/source/contributing.rst
  python/{{cookiecutter.project_slug}}/docs/source/index.rst
  python/{{cookiecutter.project_slug}}/docs/source/install.rst
  python/{{cookiecutter.project_slug}}/docs/source/reference/index.rst
  python/{{cookiecutter.project_slug}}/docs/source/usage.rst
  readthedocs_setup.md
Labels: priority:medium

#11 cicd: add gh action for requiring priority label
  .github/workflows/pr-priority-label.yaml
Labels: ci, priority:medium
